#!/usr/bin/env python3
"""A73 exact audit: complete declared one-pivot neighborhood at a common probe.

The reference late-stage signature is

    S:
      P = {0,3,4,M}
      Q = {1,h,h+1}, h=floor(M/2)
      active bands = alpha+, beta-, gamma+.

A common exact probe is used:

    s0 = 33/256,
    alpha0 = -log2(s0) ~= 2.9556058806415466.

At this point:
- M=11 and M=12 lie in their exact S phases.
- M=13 lies in its exact B phase, obtained from S by flipping gamma+ to
  gamma-.

Declared one-pivot neighborhood
-------------------------------
The audit enumerates every signature generated by exactly one of:

1. Exchange one active P contact with one inactive P contact.
2. Exchange one active Q contact with one inactive Q contact.
3. Flip the sign of one active completion band (beta or gamma).
4. Deactivate beta or gamma while one active P or Q contact leaves the
   reduced active system. This is the reduced representation of a slack
   entering the basis.

The scale variable is retained. Alpha is not flipped or deactivated. No
two-contact exchange or combined sign/contact exchange is included.

This produces:
- 75 neighbors for M=11,
- 82 neighbors for M=12,
- 89 neighbors for M=13,
for 246 declared one-pivot neighbors in total.

Each basis is evaluated exactly over the rationals at s0 and classified by:
- singular/rank mismatch,
- primal infeasibility,
- active-dual-multiplier infeasibility,
- reduced-cost infeasibility,
- inactive-observation-slack infeasibility,
- local optimality.

The classification priority only labels the first violated KKT layer. Every
negative and zero condition is also retained in the result file.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import sympy as sp


HERE = Path(__file__).resolve().parent

A72_RESULTS = HERE / "a72_local_pivot_diamond_results.json"
M11_PHASES = HERE / "a72_exact_phases_M11.json"
M12_PHASES = HERE / "a72_exact_phases_M12.json"
M13_PHASES = HERE / "a73_exact_phases_M13.json"
M13_CATALOGUE = HERE / "a73_exact_catalogue_M13.json"

S0 = sp.Rational(33, 256)


def normalized_epsilon(maximum: int) -> sp.Rational:
    mean = sp.Rational(maximum, 2)
    lower = int(sp.floor(mean))

    if mean == lower:
        lower_scale = sp.Rational(1, 2 ** lower)
    else:
        lower_scale = (
            sp.Rational(1, 2 ** lower)
            + sp.Rational(1, 2 ** (lower + 1))
        ) / 2

    return sp.factor(lower_scale / 1875)


def exact_phase_contains(
    phase: dict[str, Any],
    value: sp.Rational,
) -> bool:
    lower = sp.Rational(phase["s_lower"]["right"])
    upper = sp.Rational(phase["s_upper"]["left"])
    return bool(lower < value < upper)


def phase_signature(
    maximum: int,
    phase: dict[str, Any],
) -> dict[str, Any]:
    count = maximum + 1
    indices = phase["positive_indices"]

    return {
        "p_support": [
            index
            for index in indices
            if 0 <= index < count
        ],
        "q_support": [
            index - count
            for index in indices
            if count <= index < 2 * count
        ],
        "active_observations": phase[
            "active_observations"
        ],
    }


def reference_signature(maximum: int) -> dict[str, Any]:
    h = maximum // 2
    return {
        "p_support": [0, 3, 4, maximum],
        "q_support": [1, h, h + 1],
        "active_observations": [
            ["alpha", 1],
            ["beta", -1],
            ["gamma", 1],
        ],
    }


def gamma_flipped_signature(maximum: int) -> dict[str, Any]:
    signature = reference_signature(maximum)
    signature["active_observations"] = [
        ["alpha", 1],
        ["beta", -1],
        ["gamma", -1],
    ]
    return signature


def candidate_key(
    p_support: set[int],
    q_support: set[int],
    active_observations: tuple[tuple[str, int], ...],
) -> tuple[Any, ...]:
    return (
        tuple(sorted(p_support)),
        tuple(sorted(q_support)),
        tuple(active_observations),
    )


def generate_candidates(maximum: int) -> list[dict[str, Any]]:
    h = maximum // 2
    p_reference = {0, 3, 4, maximum}
    q_reference = {1, h, h + 1}
    active_reference = (
        ("alpha", 1),
        ("beta", -1),
        ("gamma", 1),
    )

    candidates: list[dict[str, Any]] = []
    seen: set[tuple[Any, ...]] = set()

    def add(
        kind: str,
        detail: Any,
        p_support: set[int],
        q_support: set[int],
        active_observations: tuple[tuple[str, int], ...],
        is_reference: bool = False,
    ) -> None:
        key = candidate_key(
            p_support,
            q_support,
            active_observations,
        )
        if key in seen:
            return
        seen.add(key)
        candidates.append(
            {
                "kind": kind,
                "detail": detail,
                "p_support": sorted(p_support),
                "q_support": sorted(q_support),
                "active_observations": [
                    list(item)
                    for item in active_observations
                ],
                "is_reference": is_reference,
            }
        )

    add(
        "reference",
        None,
        p_reference,
        q_reference,
        active_reference,
        is_reference=True,
    )

    for leaving in sorted(p_reference):
        for entering in range(maximum + 1):
            if entering not in p_reference:
                add(
                    "p_contact_exchange",
                    {
                        "leaving": leaving,
                        "entering": entering,
                    },
                    (p_reference - {leaving}) | {entering},
                    q_reference,
                    active_reference,
                )

    for leaving in sorted(q_reference):
        for entering in range(maximum + 1):
            if entering not in q_reference:
                add(
                    "q_contact_exchange",
                    {
                        "leaving": leaving,
                        "entering": entering,
                    },
                    p_reference,
                    (q_reference - {leaving}) | {entering},
                    active_reference,
                )

    for channel in ["beta", "gamma"]:
        flipped = tuple(
            (
                name,
                -sign if name == channel else sign,
            )
            for name, sign in active_reference
        )
        add(
            "completion_band_sign_flip",
            {"channel": channel},
            p_reference,
            q_reference,
            flipped,
        )

    for channel in ["beta", "gamma"]:
        deactivated = tuple(
            item
            for item in active_reference
            if item[0] != channel
        )

        for leaving in sorted(p_reference):
            add(
                "deactivate_band_remove_p_contact",
                {
                    "channel": channel,
                    "leaving": leaving,
                },
                p_reference - {leaving},
                q_reference,
                deactivated,
            )

        for leaving in sorted(q_reference):
            add(
                "deactivate_band_remove_q_contact",
                {
                    "channel": channel,
                    "leaving": leaving,
                },
                p_reference,
                q_reference - {leaving},
                deactivated,
            )

    return candidates


def exact_basis_evaluation(
    maximum: int,
    candidate: dict[str, Any],
) -> dict[str, Any]:
    support = list(range(maximum + 1))
    count = maximum + 1
    dimension = 2 * count + 1
    mean = sp.Rational(maximum, 2)
    epsilon = normalized_epsilon(maximum)

    p_support = set(candidate["p_support"])
    q_support = set(candidate["q_support"])
    active_observations = tuple(
        tuple(item)
        for item in candidate["active_observations"]
    )

    target = [
        sp.Rational(1, 2 ** x)
        for x in support
    ]

    transform_values = {
        "alpha": [S0 ** x for x in support],
        "beta": [
            sp.Rational(1, 2 ** (3 * x))
            for x in support
        ],
        "gamma": [
            sp.Rational(1, 2 ** (4 * x))
            for x in support
        ],
    }

    rows: list[list[sp.Expr]] = []
    rhs: list[sp.Rational] = []

    def append(
        row: list[sp.Expr],
        value: sp.Rational = sp.Rational(0),
    ) -> None:
        rows.append(row)
        rhs.append(value)

    row = [sp.Integer(0)] * dimension
    for index in support:
        row[index] = 1
    row[-1] = -1
    append(row)

    row = [sp.Integer(0)] * dimension
    for index in support:
        row[count + index] = 1
    row[-1] = -1
    append(row)

    row = [sp.Integer(0)] * dimension
    for index in support:
        row[index] = index
    row[-1] = -mean
    append(row)

    row = [sp.Integer(0)] * dimension
    for index in support:
        row[count + index] = index
    row[-1] = -mean
    append(row)

    row = [sp.Integer(0)] * dimension
    for index in support:
        row[count + index] = target[index]
    append(row, sp.Rational(1))

    for name, sign in active_observations:
        values = transform_values[name]
        row = [sp.Integer(0)] * dimension

        for index in support:
            row[index] = sign * values[index]
            row[count + index] = -sign * values[index]

        row[-1] = -2 * epsilon
        append(row)

    basic_variables = [
        *sorted(p_support),
        *[
            count + index
            for index in sorted(q_support)
        ],
        2 * count,
    ]

    if len(basic_variables) != len(rows):
        return {
            "classification": "rank_mismatch",
            "strict_local_optimum": False,
            "basic_variable_count": len(basic_variables),
            "active_row_count": len(rows),
        }

    basis = sp.Matrix(
        [
            [
                rows[row_index][column_index]
                for column_index in basic_variables
            ]
            for row_index in range(len(rows))
        ]
    )
    determinant = sp.factor(basis.det())

    if determinant == 0:
        return {
            "classification": "singular",
            "strict_local_optimum": False,
            "basis_determinant": "0",
        }

    inverse = basis.inv()
    basic_solution = inverse * sp.Matrix(rhs)

    objective = [sp.Integer(0)] * dimension
    for index in support:
        objective[index] = target[index]

    basic_objective = sp.Matrix(
        [
            objective[column_index]
            for column_index in basic_variables
        ]
    )
    dual = basis.T.inv() * basic_objective

    full_solution = [sp.Integer(0)] * dimension
    for column_index, value in zip(
        basic_variables,
        basic_solution,
    ):
        full_solution[column_index] = sp.factor(value)

    reduced_costs = [
        sp.factor(
            sum(
                rows[row_index][column_index]
                * dual[row_index]
                for row_index in range(len(rows))
            )
            - objective[column_index]
        )
        for column_index in range(dimension)
    ]

    inactive_slacks = []
    active_set = set(active_observations)

    for name in ["alpha", "beta", "gamma"]:
        values = transform_values[name]
        difference = sp.factor(
            sum(
                values[index]
                * (
                    full_solution[index]
                    - full_solution[count + index]
                )
                for index in support
            )
        )

        for sign in [1, -1]:
            if (name, sign) not in active_set:
                slack = sp.factor(
                    2
                    * epsilon
                    * full_solution[-1]
                    - sign
                    * difference
                )
                inactive_slacks.append(
                    {
                        "channel": name,
                        "sign": sign,
                        "value": slack,
                    }
                )

    negative_basic = [
        {
            "variable": basic_variables[index],
            "value": sp.factor(value),
        }
        for index, value in enumerate(basic_solution)
        if value < 0
    ]
    zero_basic = [
        basic_variables[index]
        for index, value in enumerate(basic_solution)
        if value == 0
    ]

    negative_dual = [
        {
            "observation": list(
                active_observations[row_index - 5]
            ),
            "value": sp.factor(dual[row_index]),
        }
        for row_index in range(5, len(rows))
        if dual[row_index] < 0
    ]
    zero_dual = [
        list(active_observations[row_index - 5])
        for row_index in range(5, len(rows))
        if dual[row_index] == 0
    ]

    nonbasic_variables = [
        column_index
        for column_index in range(dimension)
        if column_index not in basic_variables
    ]
    negative_reduced = [
        {
            "variable": column_index,
            "value": reduced_costs[column_index],
        }
        for column_index in nonbasic_variables
        if reduced_costs[column_index] < 0
    ]
    zero_reduced = [
        column_index
        for column_index in nonbasic_variables
        if reduced_costs[column_index] == 0
    ]

    negative_slacks = [
        item
        for item in inactive_slacks
        if item["value"] < 0
    ]
    zero_slacks = [
        {
            "channel": item["channel"],
            "sign": item["sign"],
        }
        for item in inactive_slacks
        if item["value"] == 0
    ]

    if negative_basic:
        classification = "primal_infeasible"
    elif negative_dual:
        classification = (
            "active_dual_multiplier_infeasible"
        )
    elif negative_reduced:
        classification = (
            "reduced_cost_infeasible"
        )
    elif negative_slacks:
        classification = (
            "inactive_observation_slack_infeasible"
        )
    else:
        classification = "locally_optimal"

    strict_local_optimum = bool(
        classification == "locally_optimal"
        and not zero_basic
        and not zero_dual
        and not zero_reduced
        and not zero_slacks
    )

    ratio = sp.factor(
        sum(
            objective[index]
            * full_solution[index]
            for index in range(dimension)
        )
    )

    def serialize_entries(
        entries: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        output = []

        for item in entries:
            converted = {}

            for key, value in item.items():
                converted[key] = (
                    str(value)
                    if isinstance(value, sp.Basic)
                    else value
                )

            output.append(converted)

        return output

    return {
        "classification": classification,
        "strict_local_optimum": strict_local_optimum,
        "basis_determinant": str(determinant),
        "ratio": str(ratio),
        "negative_basic": serialize_entries(
            negative_basic
        ),
        "zero_basic": zero_basic,
        "negative_active_dual": serialize_entries(
            negative_dual
        ),
        "zero_active_dual": zero_dual,
        "negative_reduced_cost": serialize_entries(
            negative_reduced
        ),
        "zero_reduced_cost": zero_reduced,
        "negative_inactive_slack": serialize_entries(
            negative_slacks
        ),
        "zero_inactive_slack": zero_slacks,
        "negative_counts": {
            "basic": len(negative_basic),
            "active_dual": len(negative_dual),
            "reduced_cost": len(negative_reduced),
            "inactive_slack": len(negative_slacks),
        },
    }


def main() -> None:
    required = [
        A72_RESULTS,
        M11_PHASES,
        M12_PHASES,
        M13_PHASES,
        M13_CATALOGUE,
    ]

    for path in required:
        if not path.exists():
            raise FileNotFoundError(path)

    a72 = json.loads(
        A72_RESULTS.read_text(encoding="utf-8")
    )
    phase_results = {
        11: json.loads(
            M11_PHASES.read_text(encoding="utf-8")
        ),
        12: json.loads(
            M12_PHASES.read_text(encoding="utf-8")
        ),
        13: json.loads(
            M13_PHASES.read_text(encoding="utf-8")
        ),
    }
    catalogue_13 = json.loads(
        M13_CATALOGUE.read_text(encoding="utf-8")
    )

    expected_probe_phases = {
        11: 4,
        12: 4,
        13: 7,
    }
    expected_probe_signatures = {
        11: reference_signature(11),
        12: reference_signature(12),
        13: gamma_flipped_signature(13),
    }

    probe_checks = {}
    all_records = []
    support_summaries = {}
    total_neighbor_counts = Counter()
    total_including_reference_counts = Counter()
    pivot_type_counts = defaultdict(Counter)

    for maximum in [11, 12, 13]:
        phase_result = phase_results[maximum]
        phase_number = expected_probe_phases[maximum]
        phase = phase_result["phases"][phase_number - 1]

        observed_signature = phase_signature(
            maximum,
            phase,
        )
        expected_signature = (
            expected_probe_signatures[maximum]
        )

        probe_checks[str(maximum)] = {
            "phase": phase_number,
            "probe_inside_phase": exact_phase_contains(
                phase,
                S0,
            ),
            "observed_signature": observed_signature,
            "expected_signature": expected_signature,
            "signature_matches": bool(
                observed_signature
                == expected_signature
            ),
        }

        candidates = generate_candidates(maximum)
        reference_count = sum(
            candidate["is_reference"]
            for candidate in candidates
        )
        neighbor_count = (
            len(candidates)
            - reference_count
        )

        counts_including_reference = Counter()
        counts_neighbors = Counter()
        strict_optima = []
        local_optima = []

        for candidate_index, candidate in enumerate(
            candidates,
            start=1,
        ):
            evaluation = exact_basis_evaluation(
                maximum,
                candidate,
            )
            record = {
                "maximum": maximum,
                "candidate_index": candidate_index,
                **candidate,
                **evaluation,
            }
            all_records.append(record)

            classification = evaluation[
                "classification"
            ]
            counts_including_reference[
                classification
            ] += 1
            total_including_reference_counts[
                classification
            ] += 1

            if not candidate["is_reference"]:
                counts_neighbors[
                    classification
                ] += 1
                total_neighbor_counts[
                    classification
                ] += 1
                pivot_type_counts[
                    candidate["kind"]
                ][classification] += 1

            if classification == "locally_optimal":
                local_optima.append(
                    {
                        "candidate_index": candidate_index,
                        "kind": candidate["kind"],
                        "detail": candidate["detail"],
                        "p_support": candidate["p_support"],
                        "q_support": candidate["q_support"],
                        "active_observations": candidate[
                            "active_observations"
                        ],
                        "strict": evaluation[
                            "strict_local_optimum"
                        ],
                    }
                )

                if evaluation[
                    "strict_local_optimum"
                ]:
                    strict_optima.append(
                        local_optima[-1]
                    )

        support_summaries[str(maximum)] = {
            "candidate_count_including_reference": len(
                candidates
            ),
            "reference_count": reference_count,
            "single_pivot_neighbor_count": neighbor_count,
            "classification_counts_including_reference": dict(
                counts_including_reference
            ),
            "classification_counts_neighbors": dict(
                counts_neighbors
            ),
            "local_optima": local_optima,
            "strict_local_optima": strict_optima,
        }

    m13_winner_ratio = sp.Rational(
        catalogue_13["top"][0]["primal"]
    )
    m13_boundary_ratio = sp.Rational(
        phase_results[13]["boundary_ratio"]
    )

    m13_reference_record = next(
        record
        for record in all_records
        if record["maximum"] == 13
        and record["is_reference"]
    )
    m13_flip_record = next(
        record
        for record in all_records
        if record["maximum"] == 13
        and record["kind"]
        == "completion_band_sign_flip"
        and record["detail"]["channel"]
        == "gamma"
    )

    gates = {
        "A72_previous_audit_passed": bool(
            all(a72["gates"].values())
        ),
        "M13_exact_phase_theorem_passed": bool(
            all(
                phase_results[13][
                    "gates"
                ].values()
            )
        ),
        "M13_exact_catalogue_has_84_designs": bool(
            catalogue_13["count"] == 84
        ),
        "M13_unique_catalogue_winner_2_3_4": bool(
            catalogue_13["winner"]
            == [2, 3, 4]
            and sp.Rational(
                catalogue_13["gap"]
            )
            > 0
        ),
        "M13_catalogue_and_continuous_boundary_values_match": bool(
            m13_winner_ratio
            == m13_boundary_ratio
        ),
        "common_probe_inside_all_expected_exact_phases": bool(
            all(
                item["probe_inside_phase"]
                for item in probe_checks.values()
            )
        ),
        "probe_signatures_match_exact_phase_certificates": bool(
            all(
                item["signature_matches"]
                for item in probe_checks.values()
            )
        ),
        "all_246_declared_neighbors_enumerated": bool(
            sum(
                summary[
                    "single_pivot_neighbor_count"
                ]
                for summary
                in support_summaries.values()
            )
            == 246
        ),
        "all_249_reference_and_neighbor_bases_classified": bool(
            len(all_records) == 249
            and not any(
                record["classification"]
                in {
                    "rank_mismatch",
                    "singular",
                }
                for record in all_records
            )
        ),
        "M11_reference_S_unique_strict_local_optimum": bool(
            support_summaries["11"][
                "strict_local_optima"
            ]
            == [
                {
                    "candidate_index": 1,
                    "kind": "reference",
                    "detail": None,
                    "p_support": [0, 3, 4, 11],
                    "q_support": [1, 5, 6],
                    "active_observations": [
                        ["alpha", 1],
                        ["beta", -1],
                        ["gamma", 1],
                    ],
                    "strict": True,
                }
            ]
        ),
        "M12_reference_S_unique_strict_local_optimum": bool(
            support_summaries["12"][
                "strict_local_optima"
            ]
            == [
                {
                    "candidate_index": 1,
                    "kind": "reference",
                    "detail": None,
                    "p_support": [0, 3, 4, 12],
                    "q_support": [1, 6, 7],
                    "active_observations": [
                        ["alpha", 1],
                        ["beta", -1],
                        ["gamma", 1],
                    ],
                    "strict": True,
                }
            ]
        ),
        "M13_gamma_sign_flip_unique_strict_local_optimum": bool(
            len(
                support_summaries["13"][
                    "strict_local_optima"
                ]
            )
            == 1
            and support_summaries["13"][
                "strict_local_optima"
            ][0]["kind"]
            == "completion_band_sign_flip"
            and support_summaries["13"][
                "strict_local_optima"
            ][0]["detail"]
            == {"channel": "gamma"}
        ),
        "M13_reference_S_rejected_by_negative_gamma_plus_multiplier": bool(
            m13_reference_record[
                "classification"
            ]
            == "active_dual_multiplier_infeasible"
            and any(
                item["observation"]
                == ["gamma", 1]
                for item
                in m13_reference_record[
                    "negative_active_dual"
                ]
            )
        ),
        "M13_selected_gamma_minus_basis_is_strictly_KKT_feasible": bool(
            m13_flip_record[
                "classification"
            ]
            == "locally_optimal"
            and m13_flip_record[
                "strict_local_optimum"
            ]
        ),
        "combined_neighbor_classification_counts_match": bool(
            dict(total_neighbor_counts)
            == {
                "primal_infeasible": 181,
                "active_dual_multiplier_infeasible": 25,
                "reduced_cost_infeasible": 37,
                "inactive_observation_slack_infeasible": 2,
                "locally_optimal": 1,
            }
        ),
    }

    verdict = (
        "PASS_COMPLETE_ONE_PIVOT_NEIGHBORHOOD_AND_M13_SIGN_SELECTION"
        if all(gates.values())
        else "FAIL_A73_ONE_PIVOT_NEIGHBORHOOD_AUDIT"
    )

    result = {
        "audit": (
            "A73_COMPLETE_ONE_PIVOT_NEIGHBORHOOD"
        ),
        "probe": {
            "s": str(S0),
            "alpha_decimal": str(
                sp.N(
                    -sp.log(S0, 2),
                    50,
                )
            ),
            "reason": (
                "The same exact rational probe lies inside the "
                "M=11 and M=12 S phases and the M=13 gamma-minus "
                "phase."
            ),
        },
        "declared_neighborhood": {
            "reference_signature": (
                "P={0,3,4,M}, Q={1,floor(M/2),floor(M/2)+1}, "
                "active={alpha+,beta-,gamma+}"
            ),
            "moves": [
                "exchange one P contact",
                "exchange one Q contact",
                "flip beta or gamma active-band sign",
                (
                    "deactivate beta or gamma while one active "
                    "P or Q contact leaves the reduced basis"
                ),
            ],
            "excluded_moves": [
                "scale-variable exchange",
                "alpha sign flip or alpha deactivation",
                "two-contact exchange",
                "combined contact exchange and band sign flip",
                "complete LP-basis enumeration",
            ],
            "neighbor_counts": {
                "11": 75,
                "12": 82,
                "13": 89,
                "total": 246,
            },
        },
        "M13_global_extension": {
            "catalogue": catalogue_13,
            "continuous_phase_result": phase_results[13],
            "formal_result": (
                "M=13 has eight exact phases, seven simple finite "
                "transitions, unique integer-catalogue winner "
                "{2,3,4}, and a strictly increasing continuous "
                "first-anchor risk on [2,3)."
            ),
        },
        "probe_checks": probe_checks,
        "support_summaries": support_summaries,
        "combined_classification_counts_neighbors": dict(
            total_neighbor_counts
        ),
        "combined_classification_counts_including_reference": dict(
            total_including_reference_counts
        ),
        "pivot_type_classification_counts": {
            kind: dict(counts)
            for kind, counts
            in pivot_type_counts.items()
        },
        "candidate_records": all_records,
        "formal_results": [
            (
                "all 246 signatures in the declared one-pivot "
                "neighborhood were generated without manual filtering"
            ),
            (
                "M=11 and M=12 have the reference S signature as "
                "their unique strict local KKT optimum at the common "
                "exact probe"
            ),
            (
                "M=13 rejects S by a negative gamma-plus active "
                "multiplier"
            ),
            (
                "the gamma sign flip is the unique strict local "
                "optimum among the 89 M=13 neighbors"
            ),
            (
                "181 neighbors fail primal feasibility before any "
                "dual or reduced-cost test is needed"
            ),
            (
                "the first exact grammar break is therefore a pure "
                "completion-band sign selection, not a hidden contact "
                "exchange or numerical tie"
            ),
            (
                "the global first-boundary theorem extends to M=13 "
                "with eight exact phases"
            ),
        ],
        "gates": gates,
        "verdict": verdict,
        "boundary": (
            "A73 is complete only for the explicitly declared "
            "one-pivot signature neighborhood at the exact probe "
            "s=33/256. It is not a complete enumeration of all LP "
            "bases or all feasible signatures across the full "
            "continuous alpha interval."
        ),
    }

    output = HERE / (
        "a73_complete_one_pivot_neighborhood_results.json"
    )
    output.write_text(
        json.dumps(
            result,
            indent=2,
        ),
        encoding="utf-8",
    )

    summary = {
        "audit": result["audit"],
        "gate_count": len(gates),
        "pass_count": sum(gates.values()),
        "probe": result["probe"],
        "neighbor_counts": result[
            "declared_neighborhood"
        ]["neighbor_counts"],
        "combined_neighbor_classification_counts": (
            result[
                "combined_classification_counts_neighbors"
            ]
        ),
        "strict_local_optima": {
            maximum: summary[
                "strict_local_optima"
            ]
            for maximum, summary
            in support_summaries.items()
        },
        "M13_phase_count": (
            phase_results[13][
                "phase_count"
            ]
        ),
        "M13_transition_count": (
            phase_results[13][
                "transition_count"
            ]
        ),
        "failed_gates": [
            name
            for name, value
            in gates.items()
            if not value
        ],
        "verdict": verdict,
    }

    print(json.dumps(summary, indent=2))

    if not all(gates.values()):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
