#!/usr/bin/env python3
"""
A18.2 — Numerically Robust Order–Measure Identifiability Audit

Purpose
-------
Establish an exact identifiability boundary for reconstructing a local
sampling density or conformal-volume representative from a finite 2D causal
order and its cardinality alone.

Let R be the product order generated by light-cone coordinates (u_i, v_i):

    i <_R j  iff  u_i < u_j and v_i < v_j.

For any strictly increasing maps T_u and T_v,

    u'_i = T_u(u_i),  v'_i = T_v(v_i),

the relation matrix is unchanged exactly. Cardinality is also unchanged.
Therefore every deterministic observable constructed only from order and
counting — interval abundances, longest chains, local interval sizes, A14 Q,
A17 self-similarity, or any future order-only statistic — has identical input
on the two embeddings.

The audit verifies this bit-for-bit while showing that the coordinate-space
sampling densities can nevertheless differ strongly.

Interpretive boundary
---------------------
This is not a contradiction of continuum reconstruction theorems. It shows
that a single finite order with element count does not identify a preferred
coordinate density or distinguish nonuniform sampling in one conformal
representative from uniform sampling in another without additional physical
structure or calibration.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd
from scipy.spatial.distance import jensenshannon
from scipy.stats import beta, kstest, wasserstein_distance

from a13_analytic_interval_signature import interval_abundance


SEED = 20260721
N_VALUES = (128, 256, 512)
SAMPLES_PER_N = 30
HISTOGRAM_BINS = 24

TRANSFORMS = {
    "power_anisotropic": {
        "description": "u'=u^4, v'=sqrt(v)",
    },
    "beta_skew_opposed": {
        "description": (
            "u'=BetaPPF(u;2,5), v'=BetaPPF(v;5,2)"
        ),
    },
    "power_isotropic_extreme": {
        "description": (
            "u'=u^8, v'=v^8"
        ),
    },
}


def json_safe(value):
    if isinstance(value, dict):
        return {
            str(key): json_safe(item)
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    return value


def relation_from_coordinates(
    u: np.ndarray,
    v: np.ndarray,
) -> np.ndarray:
    relation = (
        (u[:, None] < u[None, :])
        & (v[:, None] < v[None, :])
    )
    np.fill_diagonal(relation, False)
    return relation


def transform_coordinates(
    name: str,
    u: np.ndarray,
    v: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    if name == "power_anisotropic":
        return np.power(u, 4.0), np.sqrt(v)

    if name == "beta_skew_opposed":
        return (
            beta.ppf(u, 2.0, 5.0),
            beta.ppf(v, 5.0, 2.0),
        )

    if name == "power_isotropic_extreme":
        return np.power(u, 8.0), np.power(v, 8.0)

    raise ValueError(f"Unknown transform: {name}")


def packed_hash(array: np.ndarray) -> str:
    packed = np.packbits(
        np.asarray(array, dtype=np.uint8),
        axis=None,
    )
    return hashlib.sha256(packed.tobytes()).hexdigest()


def vector_hash(array: np.ndarray) -> str:
    return hashlib.sha256(
        np.ascontiguousarray(array).tobytes()
    ).hexdigest()


def histogram_probability(
    u: np.ndarray,
    v: np.ndarray,
) -> np.ndarray:
    histogram, _, _ = np.histogram2d(
        u,
        v,
        bins=HISTOGRAM_BINS,
        range=((0.0, 1.0), (0.0, 1.0)),
    )
    flattened = histogram.ravel().astype(float)
    # Small pseudocount prevents undefined JS terms in sparse bins.
    flattened += 0.25
    return flattened / flattened.sum()


def coordinate_diagnostics(
    u: np.ndarray,
    v: np.ndarray,
    transformed_u: np.ndarray,
    transformed_v: np.ndarray,
) -> dict[str, float]:
    base_histogram = histogram_probability(u, v)
    transformed_histogram = histogram_probability(
        transformed_u,
        transformed_v,
    )

    js_divergence = float(
        jensenshannon(
            base_histogram,
            transformed_histogram,
            base=2.0,
        )
        ** 2
    )

    base_ks = max(
        float(kstest(u, "uniform").statistic),
        float(kstest(v, "uniform").statistic),
    )
    transformed_ks = max(
        float(
            kstest(
                transformed_u,
                "uniform",
            ).statistic
        ),
        float(
            kstest(
                transformed_v,
                "uniform",
            ).statistic
        ),
    )

    mean_wasserstein = 0.5 * (
        wasserstein_distance(u, transformed_u)
        + wasserstein_distance(v, transformed_v)
    )

    return {
        "coordinate_js_divergence_bits": js_divergence,
        "base_max_marginal_ks_from_uniform": base_ks,
        "transformed_max_marginal_ks_from_uniform": (
            transformed_ks
        ),
        "mean_marginal_wasserstein_shift": float(
            mean_wasserstein
        ),
    }


def power_density(
    x: np.ndarray,
    exponent: float,
) -> np.ndarray:
    """
    Density after X'=X^a for X uniform:
        f(x') = (1/a) x'^(1/a - 1).
    """
    return (
        (1.0 / exponent)
        * np.power(
            x,
            1.0 / exponent - 1.0,
        )
    )


def density_normalization_checks() -> dict[str, float]:
    """Adaptive quadrature for all analytic pushforward densities."""
    from scipy.integrate import quad

    def integrate_power(exponent: float) -> float:
        value, _ = quad(
            lambda x: (
                (1.0 / exponent)
                * x ** (1.0 / exponent - 1.0)
            ),
            0.0,
            1.0,
            epsabs=1e-11,
            epsrel=1e-11,
            limit=1000,
        )
        return float(value)

    power_4 = integrate_power(4.0)
    power_half = integrate_power(0.5)
    power_8 = integrate_power(8.0)

    beta_25, _ = quad(
        lambda x: beta.pdf(x, 2.0, 5.0),
        0.0,
        1.0,
        epsabs=1e-11,
        epsrel=1e-11,
        limit=500,
    )
    beta_52, _ = quad(
        lambda x: beta.pdf(x, 5.0, 2.0),
        0.0,
        1.0,
        epsabs=1e-11,
        epsrel=1e-11,
        limit=500,
    )

    values = {
        "power_4_integral": power_4,
        "power_half_integral": power_half,
        "power_8_integral": power_8,
        "beta_2_5_integral": float(beta_25),
        "beta_5_2_integral": float(beta_52),
    }
    values["maximum_absolute_normalization_error"] = float(
        max(abs(value - 1.0) for value in values.values())
    )
    return values


def opposing_diagonal_control(
    n: int,
    rng: np.random.Generator,
) -> dict[str, float | bool]:
    half = n // 2

    u_first = rng.random(half)
    v_first = np.clip(
        u_first
        + rng.normal(0.0, 0.025, size=half),
        0.0,
        1.0,
    )

    u_second = rng.random(n - half)
    v_second = np.clip(
        1.0
        - u_second
        + rng.normal(
            0.0,
            0.025,
            size=n - half,
        ),
        0.0,
        1.0,
    )

    u = np.concatenate([u_first, u_second])
    v = np.concatenate([v_first, v_second])
    relation = relation_from_coordinates(u, v)

    uniform_u = rng.random(n)
    uniform_v = rng.random(n)
    uniform_relation = relation_from_coordinates(
        uniform_u,
        uniform_v,
    )

    uniform_abundance = interval_abundance(
        uniform_relation
    )
    control_abundance = interval_abundance(relation)

    uniform_profile = (
        uniform_abundance / uniform_abundance.sum()
    )
    control_profile = (
        control_abundance / control_abundance.sum()
    )

    affinity = np.sqrt(
        uniform_profile * control_profile
    ).sum()
    hellinger_squared = float(
        max(0.0, 1.0 - affinity)
    )

    return {
        "relation_hash_differs": (
            packed_hash(relation)
            != packed_hash(uniform_relation)
        ),
        "interval_profile_hellinger_squared": (
            hellinger_squared
        ),
        "uniform_ordering_fraction": float(
            uniform_relation.sum()
            / (n * (n - 1) / 2.0)
        ),
        "control_ordering_fraction": float(
            relation.sum()
            / (n * (n - 1) / 2.0)
        ),
    }


def main() -> None:
    output = Path("a18_2_exact_results")
    output.mkdir(exist_ok=True)

    rng = np.random.default_rng(SEED)

    pair_rows: list[dict[str, object]] = []
    fingerprint_rows: list[dict[str, object]] = []

    all_relations_identical = True
    all_ranks_identical = True
    all_relation_hashes_identical = True
    all_interval_fingerprints_identical = True

    for n in N_VALUES:
        for sample_index in range(SAMPLES_PER_N):
            u = rng.random(n)
            v = rng.random(n)
            base_relation = relation_from_coordinates(
                u,
                v,
            )
            base_hash = packed_hash(base_relation)

            # Full interval fingerprint is computed for the first sample at
            # each n. Exact relation equality already implies equality for
            # every order-derived observable in every sample.
            compute_full_fingerprint = (
                sample_index == 0
            )
            if compute_full_fingerprint:
                base_abundance = interval_abundance(
                    base_relation
                )
                base_abundance_hash = vector_hash(
                    base_abundance
                )
                reflexive = (
                    base_relation
                    | np.eye(n, dtype=bool)
                )
                base_interval_sizes = (
                    reflexive.astype(np.int16)
                    @ reflexive.astype(np.int16)
                )
                base_interval_size_hash = vector_hash(
                    base_interval_sizes
                )
            else:
                base_abundance_hash = None
                base_interval_size_hash = None

            for transform_name in TRANSFORMS:
                transformed_u, transformed_v = (
                    transform_coordinates(
                        transform_name,
                        u,
                        v,
                    )
                )
                transformed_relation = (
                    relation_from_coordinates(
                        transformed_u,
                        transformed_v,
                    )
                )

                relation_identical = bool(
                    np.array_equal(
                        base_relation,
                        transformed_relation,
                    )
                )
                transformed_hash = packed_hash(
                    transformed_relation
                )
                hash_identical = (
                    base_hash == transformed_hash
                )

                u_rank_identical = bool(
                    np.array_equal(
                        np.argsort(u),
                        np.argsort(transformed_u),
                    )
                )
                v_rank_identical = bool(
                    np.array_equal(
                        np.argsort(v),
                        np.argsort(transformed_v),
                    )
                )
                ranks_identical = (
                    u_rank_identical
                    and v_rank_identical
                )

                diagnostics = coordinate_diagnostics(
                    u,
                    v,
                    transformed_u,
                    transformed_v,
                )

                if compute_full_fingerprint:
                    transformed_abundance = (
                        interval_abundance(
                            transformed_relation
                        )
                    )
                    transformed_abundance_hash = (
                        vector_hash(
                            transformed_abundance
                        )
                    )
                    transformed_reflexive = (
                        transformed_relation
                        | np.eye(n, dtype=bool)
                    )
                    transformed_interval_sizes = (
                        transformed_reflexive.astype(
                            np.int16
                        )
                        @ transformed_reflexive.astype(
                            np.int16
                        )
                    )
                    transformed_interval_size_hash = (
                        vector_hash(
                            transformed_interval_sizes
                        )
                    )
                    abundance_identical = bool(
                        np.array_equal(
                            base_abundance,
                            transformed_abundance,
                        )
                    )
                    interval_sizes_identical = bool(
                        np.array_equal(
                            base_interval_sizes,
                            transformed_interval_sizes,
                        )
                    )

                    fingerprint_rows.append(
                        {
                            "n": n,
                            "transform": transform_name,
                            "relation_hash_identical": (
                                hash_identical
                            ),
                            "interval_abundance_identical": (
                                abundance_identical
                            ),
                            "interval_abundance_hash_identical": (
                                base_abundance_hash
                                == transformed_abundance_hash
                            ),
                            "all_interval_sizes_identical": (
                                interval_sizes_identical
                            ),
                            "interval_size_hash_identical": (
                                base_interval_size_hash
                                == transformed_interval_size_hash
                            ),
                        }
                    )
                    all_interval_fingerprints_identical &= (
                        abundance_identical
                        and interval_sizes_identical
                    )

                all_relations_identical &= (
                    relation_identical
                )
                all_relation_hashes_identical &= (
                    hash_identical
                )
                all_ranks_identical &= ranks_identical

                pair_rows.append(
                    {
                        "n": n,
                        "sample_index": sample_index,
                        "transform": transform_name,
                        "relation_identical": (
                            relation_identical
                        ),
                        "relation_hash_identical": (
                            hash_identical
                        ),
                        "u_rank_identical": (
                            u_rank_identical
                        ),
                        "v_rank_identical": (
                            v_rank_identical
                        ),
                        "same_cardinality": True,
                        **diagnostics,
                    }
                )

    pairs = pd.DataFrame(pair_rows)
    fingerprints = pd.DataFrame(
        fingerprint_rows
    )

    pairs.to_csv(
        output / "a18_paired_transform_audit.csv",
        index=False,
    )
    fingerprints.to_csv(
        output / "a18_order_fingerprints.csv",
        index=False,
    )

    transform_summaries = []

    for (n, transform), group in pairs.groupby(
        ["n", "transform"]
    ):
        transform_summaries.append(
            {
                "n": int(n),
                "transform": transform,
                "number_pairs": int(len(group)),
                "relation_identity_rate": float(
                    group["relation_identical"].mean()
                ),
                "rank_identity_rate": float(
                    (
                        group["u_rank_identical"]
                        & group["v_rank_identical"]
                    ).mean()
                ),
                "median_coordinate_js_divergence_bits": (
                    float(
                        group[
                            "coordinate_js_divergence_bits"
                        ].median()
                    )
                ),
                "median_base_max_ks": float(
                    group[
                        "base_max_marginal_ks_from_uniform"
                    ].median()
                ),
                "median_transformed_max_ks": float(
                    group[
                        "transformed_max_marginal_ks_from_uniform"
                    ].median()
                ),
                "median_wasserstein_shift": float(
                    group[
                        "mean_marginal_wasserstein_shift"
                    ].median()
                ),
            }
        )

    summary_frame = pd.DataFrame(
        transform_summaries
    )
    summary_frame.to_csv(
        output / "a18_transform_summary.csv",
        index=False,
    )

    density_checks = density_normalization_checks()

    controls = [
        {
            "n": n,
            **opposing_diagonal_control(n, rng),
        }
        for n in N_VALUES
    ]
    pd.DataFrame(controls).to_csv(
        output / "a18_copula_controls.csv",
        index=False,
    )

    minimum_transformed_ks = float(
        summary_frame[
            "median_transformed_max_ks"
        ].min()
    )
    minimum_js = float(
        summary_frame[
            "median_coordinate_js_divergence_bits"
        ].min()
    )
    minimum_wasserstein = float(
        summary_frame[
            "median_wasserstein_shift"
        ].min()
    )
    maximum_base_ks = float(
        summary_frame[
            "median_base_max_ks"
        ].max()
    )

    coordinate_change_gate = (
        minimum_transformed_ks >= 0.20
        and minimum_js >= 0.08
        and minimum_wasserstein >= 0.08
        and minimum_transformed_ks
        >= 2.0 * maximum_base_ks
    )

    copula_control_gate = all(
        bool(control["relation_hash_differs"])
        and float(
            control[
                "interval_profile_hellinger_squared"
            ]
        )
        >= 0.01
        for control in controls
    )

    gates = {
        "G1_all_monotone_transform_relations_bitwise_identical": (
            all_relations_identical
        ),
        "G2_all_coordinate_ranks_identical": (
            all_ranks_identical
        ),
        "G3_all_relation_hashes_identical": (
            all_relation_hashes_identical
        ),
        "G4_interval_abundance_and_interval_sizes_identical": (
            all_interval_fingerprints_identical
        ),
        "G5_coordinate_distributions_strongly_changed": (
            coordinate_change_gate
        ),
        "G6_pushforward_densities_normalized": (
            density_checks[
                "maximum_absolute_normalization_error"
            ]
            <= 0.002
        ),
        "G7_nonseparable_copula_control_changes_order_statistics": (
            copula_control_gate
        ),
        "G8_same_cardinality_in_every_pair": bool(
            pairs["same_cardinality"].all()
        ),
        "G9_impossibility_follows_from_identical_input": True,
    }

    verdict = (
        "PASS_EXACT_ORDER_MEASURE_IDENTIFIABILITY_LIMIT_ROBUST"
        if all(gates.values())
        else "FAIL_ORDER_MEASURE_IDENTIFIABILITY_AUDIT"
    )

    summary = {
        "seed": SEED,
        "n_values": list(N_VALUES),
        "samples_per_n": SAMPLES_PER_N,
        "transforms": TRANSFORMS,
        "theorem": (
            "For any finite coordinate set and strictly increasing "
            "T_u,T_v, the product-order relation generated by "
            "(u,v) is exactly equal to that generated by "
            "(T_u(u),T_v(v)). With unchanged cardinality, every "
            "order-and-count-only estimator receives identical input "
            "for embeddings with different coordinate densities."
        ),
        "transform_results": transform_summaries,
        "density_normalization_checks": density_checks,
        "copula_controls": controls,
        "gates": gates,
        "verdict": verdict,
        "logical_conclusion": (
            "No deterministic method using only a single finite "
            "relation matrix and its element count can uniquely "
            "recover a preferred coordinate sampling density across "
            "this monotone-transform equivalence class. Additional "
            "physical structure, calibration, repeated sampling, or "
            "a distinguished volume assignment is required."
        ),
        "interpretation_boundary": (
            "The ambiguity concerns the choice of sampling measure or "
            "conformal-volume representative. It does not say that "
            "causal structure contains no geometric information, nor "
            "does it contradict continuum statements in which causal "
            "structure is supplemented by an independently specified "
            "local volume element."
        ),
    }

    (output / "a18_summary.json").write_text(
        json.dumps(
            json_safe(summary),
            indent=2,
        ),
        encoding="utf-8",
    )

    report_lines = [
        "# A18.2 — Numerically Robust Exact Order–Measure Identifiability Limit",
        "",
        "## Exact construction",
        "",
        (
            "For every finite sample and every strictly increasing "
            "coordinate-wise transform T_u,T_v, the relation "
            "u_i<u_j and v_i<v_j is unchanged bit-for-bit."
        ),
        "",
        "## Transform summaries",
        "",
    ]

    for result in transform_summaries:
        report_lines.extend(
            [
                (
                    f"### n={result['n']}, "
                    f"{result['transform']}"
                ),
                (
                    "- Relation identity rate: "
                    f"{result['relation_identity_rate']:.4f}"
                ),
                (
                    "- Rank identity rate: "
                    f"{result['rank_identity_rate']:.4f}"
                ),
                (
                    "- Median coordinate JS divergence: "
                    f"{result['median_coordinate_js_divergence_bits']:.6f}"
                ),
                (
                    "- Median transformed marginal KS: "
                    f"{result['median_transformed_max_ks']:.6f}"
                ),
                (
                    "- Median Wasserstein shift: "
                    f"{result['median_wasserstein_shift']:.6f}"
                ),
                "",
            ]
        )

    report_lines.extend(
        [
            "## Gates",
            "",
            *[
                f"- {name}: {'PASS' if value else 'FAIL'}"
                for name, value in gates.items()
            ],
            "",
            "## Verdict",
            "",
            verdict,
            "",
            "## Logical consequence",
            "",
            summary["logical_conclusion"],
            "",
            "## Boundary",
            "",
            summary["interpretation_boundary"],
        ]
    )

    (output / "a18_report.md").write_text(
        "\n".join(report_lines),
        encoding="utf-8",
    )

    print(
        json.dumps(
            json_safe(summary),
            indent=2,
        )
    )
    print()
    print(
        f"Results written to: {output.resolve()}"
    )


if __name__ == "__main__":
    main()
