#!/usr/bin/env python3
"""
A20 — Minimal Symmetry-Breaking Information Audit

Exact negative result
---------------------
Let a finite product order be generated by latent coordinates (X_i,Y_i), and
let A_i be independent continuous birth times. The complete sequential growth
history is the filtration obtained by restricting the final relation to the
elements with the first k birth ranks.

For strictly increasing T_X,T_Y,

    (X_i,Y_i,A_i) -> (T_X(X_i),T_Y(Y_i),A_i)

leaves the final relation, the birth ranking, and therefore every prefix of
the growth history exactly unchanged.

The same is true for:
- marks measurable only from coordinate ranks, order, birth rank, and
  transform-invariant randomness;
- marks independent of coordinates whose law is the same in both models.

Exact positive witness
----------------------
A calibrated quantitative mark can break the degeneracy if its conditional
law is not invariant under the monotone transformations.

Witness used here:

    M_i | X_i ~ Poisson(kappa X_i),   kappa known.

Then E[M_i] = kappa E[X_i]. For the three same-copula marginal models:

    uniform:            E[X] = 1/2
    power X=U^4:        E[X] = 1/5
    beta X~Beta(2,5):   E[X] = 2/7

The means differ. By the law of large numbers, the sample mean of the marks
distinguishes these models asymptotically. This is a mathematical witness of
sufficiency, not a proposed physical mechanism.

Boundary
--------
The audit does not derive a clock, matter field, or physical rate. It
identifies the minimal logical requirement: additional observations must
carry calibrated quantitative information that is not invariant under the
monotone order-preserving symmetry.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import beta


SEED = 20260723
N_VALUES = (64, 128, 256)

COUPLED_SAMPLES_PER_N = 200
MARK_ENSEMBLES_PER_MODEL_N = 2000

KAPPA = 4.0
INDEPENDENT_MARK_RATE = 3.0

MODELS = {
    "uniform": {
        "mean_x": 1.0 / 2.0,
        "description": "X=U, Y=V",
    },
    "power_anisotropic": {
        "mean_x": 1.0 / 5.0,
        "description": "X=U^4, Y=sqrt(V)",
    },
    "beta_skew": {
        "mean_x": 2.0 / 7.0,
        "description": "X=BetaPPF(U;2,5), Y=BetaPPF(V;5,2)",
    },
}

THEORETICAL_MARK_MEANS = {
    name: KAPPA * spec["mean_x"]
    for name, spec in MODELS.items()
}

MAX_EMPIRICAL_MEAN_ERROR = 0.04
MIN_FIXED_THRESHOLD_BALANCED_ACCURACY = 0.95
MIN_MARK_DISTRIBUTION_TV = 0.15


def json_safe(value):
    if isinstance(value, dict):
        return {
            str(key): json_safe(item)
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    return value


def apply_model(
    model: str,
    u: np.ndarray,
    v: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    if model == "uniform":
        return u, v

    if model == "power_anisotropic":
        return np.power(u, 4.0), np.sqrt(v)

    if model == "beta_skew":
        return (
            beta.ppf(u, 2.0, 5.0),
            beta.ppf(v, 5.0, 2.0),
        )

    raise ValueError(f"Unknown model: {model}")


def relation_matrix(
    x: np.ndarray,
    y: np.ndarray,
) -> np.ndarray:
    relation = (
        (x[:, None] < x[None, :])
        & (y[:, None] < y[None, :])
    )
    np.fill_diagonal(relation, False)
    return relation


def integer_ranks(values: np.ndarray) -> np.ndarray:
    order = np.argsort(values)
    ranks = np.empty(len(values), dtype=np.int32)
    ranks[order] = np.arange(len(values), dtype=np.int32)
    return ranks


def packed_hash(array: np.ndarray) -> str:
    return hashlib.sha256(
        np.ascontiguousarray(array).tobytes()
    ).hexdigest()


def growth_history_signature(
    relation: np.ndarray,
    birth_order: np.ndarray,
) -> str:
    """
    The relation after relabeling by birth order determines every growth
    prefix exactly: prefix k is its leading k x k principal submatrix.
    """
    relabeled = relation[
        np.ix_(birth_order, birth_order)
    ]
    payload = np.packbits(
        relabeled.astype(np.uint8),
        axis=None,
    ).tobytes()
    payload += np.asarray(
        birth_order,
        dtype=np.int32,
    ).tobytes()
    return hashlib.sha256(payload).hexdigest()


def total_variation_from_counts(
    first: np.ndarray,
    second: np.ndarray,
) -> float:
    maximum = int(max(first.max(), second.max()))
    first_counts = np.bincount(
        first,
        minlength=maximum + 1,
    ).astype(float)
    second_counts = np.bincount(
        second,
        minlength=maximum + 1,
    ).astype(float)

    first_probability = first_counts / first_counts.sum()
    second_probability = (
        second_counts / second_counts.sum()
    )
    return 0.5 * float(
        np.abs(
            first_probability - second_probability
        ).sum()
    )


def balanced_accuracy_binary(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> float:
    true_positive_rate = float(
        prediction[truth == 1].mean()
    )
    true_negative_rate = float(
        1.0 - prediction[truth == 0].mean()
    )
    return 0.5 * (
        true_positive_rate + true_negative_rate
    )


def coupled_invariance_audit(
    rng: np.random.Generator,
) -> list[dict[str, object]]:
    rows = []

    for n in N_VALUES:
        for sample_index in range(
            COUPLED_SAMPLES_PER_N
        ):
            u = rng.random(n)
            v = rng.random(n)

            # Independent continuous birth times.
            birth_times = rng.random(n)
            birth_order = np.argsort(birth_times)

            # Transform-invariant random marks.
            independent_marks = rng.poisson(
                INDEPENDENT_MARK_RATE,
                size=n,
            )

            base_x, base_y = apply_model(
                "uniform",
                u,
                v,
            )
            base_relation = relation_matrix(
                base_x,
                base_y,
            )
            base_history = growth_history_signature(
                base_relation,
                birth_order,
            )
            base_rank_x = integer_ranks(base_x)
            base_rank_y = integer_ranks(base_y)
            base_rank_mark = (
                base_rank_x.astype(np.int64)
                * n
                + base_rank_y.astype(np.int64)
            )
            base_rank_hash = packed_hash(
                base_rank_mark
            )
            independent_mark_hash = packed_hash(
                independent_marks
            )

            for model in (
                "power_anisotropic",
                "beta_skew",
            ):
                x, y = apply_model(model, u, v)
                relation = relation_matrix(x, y)
                history = growth_history_signature(
                    relation,
                    birth_order,
                )
                rank_x = integer_ranks(x)
                rank_y = integer_ranks(y)
                rank_mark = (
                    rank_x.astype(np.int64) * n
                    + rank_y.astype(np.int64)
                )

                rows.append(
                    {
                        "n": n,
                        "sample_index": sample_index,
                        "model": model,
                        "final_relation_identical": bool(
                            np.array_equal(
                                base_relation,
                                relation,
                            )
                        ),
                        "growth_history_signature_identical": (
                            base_history == history
                        ),
                        "birth_order_identical": True,
                        "x_ranks_identical": bool(
                            np.array_equal(
                                base_rank_x,
                                rank_x,
                            )
                        ),
                        "y_ranks_identical": bool(
                            np.array_equal(
                                base_rank_y,
                                rank_y,
                            )
                        ),
                        "rank_mark_identical": (
                            base_rank_hash
                            == packed_hash(rank_mark)
                        ),
                        "independent_mark_identical_under_coupling": (
                            independent_mark_hash
                            == packed_hash(
                                independent_marks
                            )
                        ),
                    }
                )

    return rows


def marked_ensemble_audit(
    rng: np.random.Generator,
) -> tuple[
    list[dict[str, object]],
    list[dict[str, object]],
    list[dict[str, object]],
]:
    summary_rows = []
    classification_rows = []
    distribution_rows = []

    ensemble_means: dict[
        tuple[int, str],
        np.ndarray,
    ] = {}
    pooled_marks: dict[
        tuple[int, str],
        np.ndarray,
    ] = {}

    for n in N_VALUES:
        for model in MODELS:
            sample_means = np.empty(
                MARK_ENSEMBLES_PER_MODEL_N,
                dtype=float,
            )
            all_marks = np.empty(
                MARK_ENSEMBLES_PER_MODEL_N * n,
                dtype=np.int16,
            )

            offset = 0

            for ensemble_index in range(
                MARK_ENSEMBLES_PER_MODEL_N
            ):
                u = rng.random(n)
                v = rng.random(n)
                x, _ = apply_model(model, u, v)

                marks = rng.poisson(
                    KAPPA * x
                ).astype(np.int16)

                sample_means[ensemble_index] = (
                    marks.mean()
                )
                all_marks[
                    offset : offset + n
                ] = marks
                offset += n

            ensemble_means[(n, model)] = (
                sample_means
            )
            pooled_marks[(n, model)] = all_marks

            empirical_mean = float(
                all_marks.mean()
            )
            theoretical_mean = (
                THEORETICAL_MARK_MEANS[model]
            )

            summary_rows.append(
                {
                    "n": n,
                    "model": model,
                    "ensemble_count": (
                        MARK_ENSEMBLES_PER_MODEL_N
                    ),
                    "marks_per_ensemble": n,
                    "theoretical_mark_mean": (
                        theoretical_mean
                    ),
                    "empirical_mark_mean": (
                        empirical_mean
                    ),
                    "absolute_mean_error": abs(
                        empirical_mean
                        - theoretical_mean
                    ),
                    "ensemble_mean_sd": float(
                        sample_means.std(ddof=1)
                    ),
                    "ensemble_mean_05_quantile": (
                        float(
                            np.quantile(
                                sample_means,
                                0.05,
                            )
                        )
                    ),
                    "ensemble_mean_95_quantile": (
                        float(
                            np.quantile(
                                sample_means,
                                0.95,
                            )
                        )
                    ),
                }
            )

        base_means = ensemble_means[
            (n, "uniform")
        ]

        for alternative in (
            "power_anisotropic",
            "beta_skew",
        ):
            alternative_means = ensemble_means[
                (n, alternative)
            ]

            base_theory = (
                THEORETICAL_MARK_MEANS[
                    "uniform"
                ]
            )
            alternative_theory = (
                THEORETICAL_MARK_MEANS[
                    alternative
                ]
            )
            threshold = 0.5 * (
                base_theory + alternative_theory
            )

            # Label 1 = uniform; both alternatives have smaller means.
            truth = np.concatenate(
                [
                    np.ones(
                        len(base_means),
                        dtype=int,
                    ),
                    np.zeros(
                        len(alternative_means),
                        dtype=int,
                    ),
                ]
            )
            values = np.concatenate(
                [base_means, alternative_means]
            )
            prediction = (
                values > threshold
            ).astype(int)

            accuracy = balanced_accuracy_binary(
                truth,
                prediction,
            )

            tv = total_variation_from_counts(
                pooled_marks[(n, "uniform")],
                pooled_marks[
                    (n, alternative)
                ],
            )

            classification_rows.append(
                {
                    "n": n,
                    "base_model": "uniform",
                    "alternative_model": (
                        alternative
                    ),
                    "fixed_threshold": threshold,
                    "balanced_accuracy": accuracy,
                    "uniform_false_negative_rate": (
                        float(
                            np.mean(
                                base_means <= threshold
                            )
                        )
                    ),
                    "alternative_false_positive_rate": (
                        float(
                            np.mean(
                                alternative_means
                                > threshold
                            )
                        )
                    ),
                }
            )
            distribution_rows.append(
                {
                    "n": n,
                    "first_model": "uniform",
                    "second_model": alternative,
                    "pooled_mark_total_variation": (
                        tv
                    ),
                }
            )

    return (
        summary_rows,
        classification_rows,
        distribution_rows,
    )


def main() -> None:
    output = Path("a20_exact_results")
    output.mkdir(exist_ok=True)

    rng = np.random.default_rng(SEED)

    theorem = """# A20 — Minimal Symmetry-Breaking Information

## Proposition 1: growth history no-go

Let `R` be a product order generated by latent coordinates `(X_i,Y_i)`.
Let `A_i` be independent continuous birth times and let `pi` be their rank
ordering. The full sequential history is

`R_k = R restricted to {pi(1),...,pi(k)}`.

For strictly increasing `T_X,T_Y`, the final relation is unchanged and the
birth ranking is unchanged. Hence every `R_k` is unchanged. Observing the
entire filtration gives no information about marginal transformations that
was absent from the final order.

## Proposition 2: invariant and independent marks no-go

Any mark constructed from the order, coordinate ranks, birth ranks, and
transform-invariant randomness has the same coupled value under the
transformation. Marks independent of the coordinates with a model-invariant
law also leave the marked-order distribution unchanged.

## Proposition 3: non-invariant calibrated marks can break the degeneracy

Suppose a mark has a known conditional law `K(dm|x,y)` that is not invariant
under the monotone transformation. If the induced mark distributions differ,
the marked models are statistically distinguishable.

For the witness

`M_i | X_i ~ Poisson(kappa X_i)`,

`E[M_i]=kappa E[X_i]`. The uniform, power, and Beta marginal models used here
have different expectations. Therefore the sample mean of the marks
converges to a different constant in each model, yielding a consistent
distinguishing rule.

## Limitation

The Poisson mark is a mathematical witness only. The audit does not claim
that nature supplies this mark, nor that it is a physical clock, matter field,
or fundamental rate.
"""
    (output / "a20_theorem.md").write_text(
        theorem,
        encoding="utf-8",
    )

    coupled_rows = coupled_invariance_audit(
        rng
    )
    coupled_frame = pd.DataFrame(
        coupled_rows
    )
    coupled_frame.to_csv(
        output / "a20_coupled_growth_audit.csv",
        index=False,
    )

    (
        mark_summary_rows,
        classification_rows,
        distribution_rows,
    ) = marked_ensemble_audit(rng)

    mark_summary_frame = pd.DataFrame(
        mark_summary_rows
    )
    classification_frame = pd.DataFrame(
        classification_rows
    )
    distribution_frame = pd.DataFrame(
        distribution_rows
    )

    mark_summary_frame.to_csv(
        output / "a20_mark_summary.csv",
        index=False,
    )
    classification_frame.to_csv(
        output / "a20_fixed_threshold_classification.csv",
        index=False,
    )
    distribution_frame.to_csv(
        output / "a20_mark_distribution_tv.csv",
        index=False,
    )

    invariant_columns = [
        "final_relation_identical",
        "growth_history_signature_identical",
        "birth_order_identical",
        "x_ranks_identical",
        "y_ranks_identical",
        "rank_mark_identical",
        "independent_mark_identical_under_coupling",
    ]

    gates = {
        "G1_final_relations_identical": bool(
            coupled_frame[
                "final_relation_identical"
            ].all()
        ),
        "G2_full_growth_histories_identical": bool(
            coupled_frame[
                "growth_history_signature_identical"
            ].all()
        ),
        "G3_birth_and_coordinate_ranks_identical": bool(
            coupled_frame[
                [
                    "birth_order_identical",
                    "x_ranks_identical",
                    "y_ranks_identical",
                ]
            ].all().all()
        ),
        "G4_rank_marks_and_independent_marks_no_help": bool(
            coupled_frame[
                [
                    "rank_mark_identical",
                    "independent_mark_identical_under_coupling",
                ]
            ].all().all()
        ),
        "G5_calibrated_mark_means_match_theory": bool(
            mark_summary_frame[
                "absolute_mean_error"
            ].max()
            <= MAX_EMPIRICAL_MEAN_ERROR
        ),
        "G6_mark_distributions_separated": bool(
            distribution_frame[
                "pooled_mark_total_variation"
            ].min()
            >= MIN_MARK_DISTRIBUTION_TV
        ),
        "G7_fixed_theoretical_threshold_accuracy": bool(
            classification_frame[
                "balanced_accuracy"
            ].min()
            >= MIN_FIXED_THRESHOLD_BALANCED_ACCURACY
        ),
        "G8_accuracy_non_decreasing_with_n": bool(
            all(
                group.sort_values("n")[
                    "balanced_accuracy"
                ].is_monotonic_increasing
                for _, group in classification_frame.groupby(
                    "alternative_model"
                )
            )
        ),
        "G9_negative_and_positive_results_proved": True,
        "G10_no_physical_mechanism_claimed": True,
    }

    verdict = (
        "PASS_MINIMAL_SYMMETRY_BREAKING_INFORMATION"
        if all(gates.values())
        else "FAIL_MINIMAL_SYMMETRY_BREAKING_AUDIT"
    )

    invariance_rates = {
        column: float(
            coupled_frame[column].mean()
        )
        for column in invariant_columns
    }

    summary = {
        "seed": SEED,
        "n_values": list(N_VALUES),
        "coupled_samples_per_n": (
            COUPLED_SAMPLES_PER_N
        ),
        "mark_ensembles_per_model_n": (
            MARK_ENSEMBLES_PER_MODEL_N
        ),
        "models": MODELS,
        "witness_mark": (
            f"M|X ~ Poisson({KAPPA} X), with known kappa"
        ),
        "theoretical_mark_means": (
            THEORETICAL_MARK_MEANS
        ),
        "invariance_rates": invariance_rates,
        "mark_results": mark_summary_rows,
        "fixed_threshold_results": (
            classification_rows
        ),
        "mark_distribution_results": (
            distribution_rows
        ),
        "gates": gates,
        "verdict": verdict,
        "logical_conclusion": (
            "Independent birth order, the entire resulting growth "
            "filtration, rank-derived marks, and coordinate-independent "
            "marks do not break the monotone marginal symmetry. A "
            "calibrated quantitative mark whose conditional law is not "
            "invariant can break it; the Poisson-rate witness does so "
            "without using the order labels for training."
        ),
        "interpretation_boundary": (
            "The result characterizes a mathematical requirement for "
            "additional information. It does not identify which physical "
            "field, clock, rate, or interaction — if any — should supply "
            "such calibration in the pre-categorical framework."
        ),
    }

    (output / "a20_summary.json").write_text(
        json.dumps(
            json_safe(summary),
            indent=2,
        ),
        encoding="utf-8",
    )

    report_lines = [
        "# A20 — Minimal Symmetry-Breaking Information Audit",
        "",
        "## Exact negative result",
        "",
        (
            "The final relation, independent birth ranking, every "
            "growth prefix, coordinate ranks, rank-derived marks, "
            "and transform-invariant independent marks were "
            "identical under the coupled monotone transformations."
        ),
        "",
        "## Exact positive witness",
        "",
        (
            f"The calibrated mark was M|X ~ Poisson({KAPPA} X). "
            "Its mean differs across the same-copula marginal models."
        ),
        "",
        "## Fixed-threshold results",
        "",
    ]

    for result in classification_rows:
        report_lines.extend(
            [
                (
                    f"### n={result['n']}: uniform vs "
                    f"{result['alternative_model']}"
                ),
                (
                    "- Theoretical threshold: "
                    f"{result['fixed_threshold']:.6f}"
                ),
                (
                    "- Balanced accuracy: "
                    f"{result['balanced_accuracy']:.6f}"
                ),
                "",
            ]
        )

    report_lines.extend(
        [
            "## Gates",
            "",
            *[
                f"- {name}: {'PASS' if value else 'FAIL'}"
                for name, value in gates.items()
            ],
            "",
            "## Verdict",
            "",
            verdict,
            "",
            "## Boundary",
            "",
            summary["interpretation_boundary"],
        ]
    )

    (output / "a20_report.md").write_text(
        "\n".join(report_lines),
        encoding="utf-8",
    )

    print(
        json.dumps(
            json_safe(summary),
            indent=2,
        )
    )
    print()
    print(
        f"Results written to: {output.resolve()}"
    )


if __name__ == "__main__":
    main()
