#!/usr/bin/env python3
"""
A21 — Equivariance of Endogenous Relational Dynamics

Exact theorem
-------------
Let O_t be the complete observed relational history through step t. Let the
next state be generated by

    O_{t+1} = Phi_t(O_0,...,O_t, Xi_t),

where Xi_t is fresh model-independent randomness and Phi_t has access only to
the observed relational history and endogenous state measurable from it.

If two latent models are related by a transformation that leaves O_0
identical, then under the coupling that uses the same Xi_t at every step,

    O_t^(1) = O_t^(2)  for every t

by induction. Hence their trajectory laws are identical. This covers Markov
and history-dependent kernels, deterministic or stochastic.

Computational audit
-------------------
Initial orders are generated from the same latent (U,V) under three marginal
representatives:
    uniform;
    X=U^4, Y=sqrt(V);
    X=BetaPPF(U;2,5), Y=BetaPPF(V;5,2).

Four endogenous growth kernels are tested:
    1. principal-ideal anchor;
    2. union of two principal ideals;
    3. random seed set followed by downward closure;
    4. history-reinforced principal-ideal anchor.

All use the same random tape across coupled representatives.

Positive control
----------------
A fifth kernel selects its anchor with probabilities proportional to

    exp(beta * Z_i),

where Z is an externally calibrated quantitative mark. Under different
marginal representatives, Z changes even when the order does not. This kernel
is expected to break trajectory identity.

Boundary
--------
The positive control is a mathematical witness, not a proposed physical
dynamics. A pass proves a symmetry restriction on order-endogenous kernels;
it does not identify a fundamental law or a physical clock.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import beta


SEED = 20260724

INITIAL_N = 24
GROWTH_STEPS = 40
COUPLED_SAMPLES = 250

ENDOGENOUS_KERNELS = (
    "principal_ideal",
    "two_ideal_union",
    "random_downset",
    "history_reinforced",
)

TRANSFORMED_MODELS = (
    "power_anisotropic",
    "beta_skew",
)

EXOGENOUS_BETA = 7.0
RANDOM_DOWNSET_SEED_PROBABILITY = 0.16

MIN_EXOGENOUS_DIVERGENCE_RATE = 0.90
MAX_MEDIAN_FIRST_DIVERGENCE_STEP = 10.0


def json_safe(value):
    if isinstance(value, dict):
        return {
            str(key): json_safe(item)
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    return value


def apply_model(
    model: str,
    u: np.ndarray,
    v: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    if model == "uniform":
        return u, v

    if model == "power_anisotropic":
        return np.power(u, 4.0), np.sqrt(v)

    if model == "beta_skew":
        return (
            beta.ppf(u, 2.0, 5.0),
            beta.ppf(v, 5.0, 2.0),
        )

    raise ValueError(f"Unknown model: {model}")


def transform_mark(
    model: str,
    u: np.ndarray,
) -> np.ndarray:
    if model == "uniform":
        return u.copy()

    if model == "power_anisotropic":
        return np.power(u, 4.0)

    if model == "beta_skew":
        return beta.ppf(u, 2.0, 5.0)

    raise ValueError(f"Unknown model: {model}")


def relation_matrix(
    x: np.ndarray,
    y: np.ndarray,
) -> np.ndarray:
    relation = (
        (x[:, None] < x[None, :])
        & (y[:, None] < y[None, :])
    )
    np.fill_diagonal(relation, False)
    return relation


def relation_hash(relation: np.ndarray) -> str:
    return hashlib.sha256(
        np.packbits(
            relation.astype(np.uint8),
            axis=None,
        ).tobytes()
    ).hexdigest()


def path_hash(
    step_hashes: list[str],
) -> str:
    return hashlib.sha256(
        "|".join(step_hashes).encode("utf-8")
    ).hexdigest()


def is_transitive(
    relation: np.ndarray,
) -> bool:
    two_step = (
        relation.astype(np.int16)
        @ relation.astype(np.int16)
    ) > 0
    return not bool(
        np.any(two_step & ~relation)
    )


def categorical_choice(
    weights: np.ndarray,
    uniform_value: float,
) -> int:
    weights = np.asarray(weights, dtype=float)

    if np.any(weights < 0.0):
        raise ValueError("Categorical weights must be nonnegative.")

    total = float(weights.sum())
    if not math.isfinite(total) or total <= 0.0:
        raise ValueError("Categorical weights have invalid total.")

    target = min(
        uniform_value,
        np.nextafter(1.0, 0.0),
    ) * total
    index = int(
        np.searchsorted(
            np.cumsum(weights),
            target,
            side="right",
        )
    )
    return min(index, len(weights) - 1)


def principal_ideal(
    relation: np.ndarray,
    anchor: int,
) -> np.ndarray:
    downset = relation[:, anchor].copy()
    downset[anchor] = True
    return downset


def add_maximal_vertex(
    relation: np.ndarray,
    downset: np.ndarray,
) -> np.ndarray:
    n = len(relation)
    updated = np.zeros(
        (n + 1, n + 1),
        dtype=bool,
    )
    updated[:n, :n] = relation
    updated[:n, n] = downset
    return updated


def build_random_tape(
    rng: np.random.Generator,
) -> dict[str, np.ndarray]:
    maximum_n = INITIAL_N + GROWTH_STEPS

    return {
        "anchor_1": rng.random(GROWTH_STEPS),
        "anchor_2": rng.random(GROWTH_STEPS),
        "subset": rng.random(
            (GROWTH_STEPS, maximum_n)
        ),
        "new_mark_latent": rng.random(GROWTH_STEPS),
    }


def run_endogenous_kernel(
    initial_relation: np.ndarray,
    kernel: str,
    tape: dict[str, np.ndarray],
) -> dict[str, object]:
    relation = initial_relation.copy()
    step_hashes = [relation_hash(relation)]
    selected_actions: list[str] = []
    transitive_every_step = is_transitive(relation)

    selection_counts = np.zeros(
        len(relation),
        dtype=np.int64,
    )

    for step in range(GROWTH_STEPS):
        n = len(relation)
        past_counts = relation.sum(
            axis=0
        ).astype(float)
        future_counts = relation.sum(
            axis=1
        ).astype(float)

        if kernel == "principal_ideal":
            weights = 1.0 + past_counts
            anchor = categorical_choice(
                weights,
                float(tape["anchor_1"][step]),
            )
            downset = principal_ideal(
                relation,
                anchor,
            )
            action = f"a:{anchor}"

        elif kernel == "two_ideal_union":
            first_anchor = categorical_choice(
                1.0 + past_counts,
                float(tape["anchor_1"][step]),
            )
            second_anchor = categorical_choice(
                1.0 + future_counts,
                float(tape["anchor_2"][step]),
            )
            downset = (
                principal_ideal(
                    relation,
                    first_anchor,
                )
                | principal_ideal(
                    relation,
                    second_anchor,
                )
            )
            action = (
                f"a1:{first_anchor}|a2:{second_anchor}"
            )

        elif kernel == "random_downset":
            seed_vertices = (
                tape["subset"][step, :n]
                < RANDOM_DOWNSET_SEED_PROBABILITY
            )
            downset = seed_vertices.copy()

            for seed in np.flatnonzero(
                seed_vertices
            ):
                downset |= principal_ideal(
                    relation,
                    int(seed),
                )

            action = (
                "seeds:"
                + ",".join(
                    str(int(vertex))
                    for vertex in np.flatnonzero(
                        seed_vertices
                    )
                )
            )

        elif kernel == "history_reinforced":
            weights = (
                1.0
                + past_counts
                + selection_counts.astype(float)
            )
            anchor = categorical_choice(
                weights,
                float(tape["anchor_1"][step]),
            )
            downset = principal_ideal(
                relation,
                anchor,
            )
            selection_counts[anchor] += 1
            action = (
                f"a:{anchor}|count:"
                f"{selection_counts[anchor]}"
            )

        else:
            raise ValueError(
                f"Unknown endogenous kernel: {kernel}"
            )

        relation = add_maximal_vertex(
            relation,
            downset,
        )
        selection_counts = np.append(
            selection_counts,
            0,
        )
        selected_actions.append(action)
        step_hashes.append(
            relation_hash(relation)
        )
        transitive_every_step &= is_transitive(
            relation
        )

    return {
        "final_relation": relation,
        "step_hashes": step_hashes,
        "path_hash": path_hash(step_hashes),
        "actions": selected_actions,
        "action_hash": hashlib.sha256(
            "|".join(
                selected_actions
            ).encode("utf-8")
        ).hexdigest(),
        "transitive_every_step": (
            transitive_every_step
        ),
    }


def run_exogenous_mark_kernel(
    initial_relation: np.ndarray,
    initial_marks: np.ndarray,
    model: str,
    tape: dict[str, np.ndarray],
) -> dict[str, object]:
    relation = initial_relation.copy()
    marks = initial_marks.copy()
    step_hashes = [relation_hash(relation)]
    selected_anchors: list[int] = []
    transitive_every_step = is_transitive(relation)

    for step in range(GROWTH_STEPS):
        centered = marks - float(marks.max())
        weights = np.exp(
            EXOGENOUS_BETA * centered
        )
        anchor = categorical_choice(
            weights,
            float(tape["anchor_1"][step]),
        )
        downset = principal_ideal(
            relation,
            anchor,
        )
        relation = add_maximal_vertex(
            relation,
            downset,
        )

        latent_new_mark = np.asarray(
            [tape["new_mark_latent"][step]],
            dtype=float,
        )
        transformed_new_mark = transform_mark(
            model,
            latent_new_mark,
        )[0]
        marks = np.append(
            marks,
            transformed_new_mark,
        )

        selected_anchors.append(anchor)
        step_hashes.append(
            relation_hash(relation)
        )
        transitive_every_step &= is_transitive(
            relation
        )

    return {
        "final_relation": relation,
        "step_hashes": step_hashes,
        "path_hash": path_hash(step_hashes),
        "anchors": selected_anchors,
        "anchor_hash": hashlib.sha256(
            np.asarray(
                selected_anchors,
                dtype=np.int32,
            ).tobytes()
        ).hexdigest(),
        "transitive_every_step": (
            transitive_every_step
        ),
    }


def first_divergence_step(
    first_hashes: list[str],
    second_hashes: list[str],
) -> int | None:
    for index, (
        first_hash,
        second_hash,
    ) in enumerate(
        zip(first_hashes, second_hashes)
    ):
        if first_hash != second_hash:
            # Index zero is the initial state.
            return index
    return None


def main() -> None:
    output = Path("a21_exact_results")
    output.mkdir(exist_ok=True)

    theorem_text = """# A21 — Equivariance Theorem for Endogenous Relational Dynamics

## Setting

Let `O_t` denote the complete observed relational history through time `t`.
Allow an arbitrary endogenous internal state `S_t`, provided `S_t` is
measurable with respect to the observed history and previous
model-independent random variables.

Let

`(O_{t+1},S_{t+1}) = Phi_t(O_0,...,O_t,S_t,Xi_t)`,

where `Xi_t` is fresh randomness with the same law in both latent models.

## Theorem

Suppose a latent transformation leaves the initial observed state and
endogenous state identical. Couple the two models with the same sequence
`Xi_0,Xi_1,...`. Then their complete observed trajectories and endogenous
states are identical almost surely.

## Proof

At time zero, the observed and endogenous states agree by assumption.
Assume they agree through time `t`. The two copies feed identical arguments
and the same `Xi_t` into the same measurable update map `Phi_t`. Their next
observed and endogenous states are therefore identical. Induction gives
identity for all finite times.

Consequently the two trajectory laws are equal. No statistic of the complete
order-valued path can distinguish the latent representatives.

## Scope

The result covers Markov and non-Markov dynamics, reinforcement, adaptive
rules, random attachment, and any other kernel whose state and transition
probabilities are functions only of the relational history and
model-independent randomness.

## Necessary route to symmetry breaking

A transition can break the degeneracy only if it depends on an additional
variable whose value or conditional law is not measurable from the
relational history and is not invariant under the latent transformation.

This is a necessary logical condition, not a proposed physical mechanism.
"""
    (output / "a21_theorem.md").write_text(
        theorem_text,
        encoding="utf-8",
    )

    rng = np.random.default_rng(SEED)

    endogenous_rows: list[
        dict[str, object]
    ] = []
    exogenous_rows: list[
        dict[str, object]
    ] = []

    for sample_index in range(
        COUPLED_SAMPLES
    ):
        latent_u = rng.random(INITIAL_N)
        latent_v = rng.random(INITIAL_N)
        tape = build_random_tape(rng)

        base_x, base_y = apply_model(
            "uniform",
            latent_u,
            latent_v,
        )
        base_relation = relation_matrix(
            base_x,
            base_y,
        )
        base_marks = transform_mark(
            "uniform",
            latent_u,
        )

        for transformed_model in (
            TRANSFORMED_MODELS
        ):
            transformed_x, transformed_y = (
                apply_model(
                    transformed_model,
                    latent_u,
                    latent_v,
                )
            )
            transformed_relation = (
                relation_matrix(
                    transformed_x,
                    transformed_y,
                )
            )
            transformed_marks = transform_mark(
                transformed_model,
                latent_u,
            )

            initial_relation_identical = bool(
                np.array_equal(
                    base_relation,
                    transformed_relation,
                )
            )

            for kernel in ENDOGENOUS_KERNELS:
                base_result = (
                    run_endogenous_kernel(
                        base_relation,
                        kernel,
                        tape,
                    )
                )
                transformed_result = (
                    run_endogenous_kernel(
                        transformed_relation,
                        kernel,
                        tape,
                    )
                )

                divergence = (
                    first_divergence_step(
                        base_result[
                            "step_hashes"
                        ],
                        transformed_result[
                            "step_hashes"
                        ],
                    )
                )

                endogenous_rows.append(
                    {
                        "sample_index": (
                            sample_index
                        ),
                        "transformed_model": (
                            transformed_model
                        ),
                        "kernel": kernel,
                        "initial_relation_identical": (
                            initial_relation_identical
                        ),
                        "all_prefix_relations_identical": (
                            divergence is None
                        ),
                        "final_relation_identical": bool(
                            np.array_equal(
                                base_result[
                                    "final_relation"
                                ],
                                transformed_result[
                                    "final_relation"
                                ],
                            )
                        ),
                        "path_hash_identical": (
                            base_result["path_hash"]
                            == transformed_result[
                                "path_hash"
                            ]
                        ),
                        "action_hash_identical": (
                            base_result[
                                "action_hash"
                            ]
                            == transformed_result[
                                "action_hash"
                            ]
                        ),
                        "first_divergence_step": (
                            divergence
                        ),
                        "base_transitive_every_step": (
                            base_result[
                                "transitive_every_step"
                            ]
                        ),
                        "transformed_transitive_every_step": (
                            transformed_result[
                                "transitive_every_step"
                            ]
                        ),
                    }
                )

            base_exogenous = (
                run_exogenous_mark_kernel(
                    base_relation,
                    base_marks,
                    "uniform",
                    tape,
                )
            )
            transformed_exogenous = (
                run_exogenous_mark_kernel(
                    transformed_relation,
                    transformed_marks,
                    transformed_model,
                    tape,
                )
            )
            divergence = first_divergence_step(
                base_exogenous["step_hashes"],
                transformed_exogenous[
                    "step_hashes"
                ],
            )

            exogenous_rows.append(
                {
                    "sample_index": sample_index,
                    "transformed_model": (
                        transformed_model
                    ),
                    "initial_relation_identical": (
                        initial_relation_identical
                    ),
                    "mark_vector_identical": bool(
                        np.array_equal(
                            base_marks,
                            transformed_marks,
                        )
                    ),
                    "trajectory_diverged": (
                        divergence is not None
                    ),
                    "first_divergence_step": (
                        divergence
                    ),
                    "final_relation_identical": bool(
                        np.array_equal(
                            base_exogenous[
                                "final_relation"
                            ],
                            transformed_exogenous[
                                "final_relation"
                            ],
                        )
                    ),
                    "path_hash_identical": (
                        base_exogenous[
                            "path_hash"
                        ]
                        == transformed_exogenous[
                            "path_hash"
                        ]
                    ),
                    "anchor_hash_identical": (
                        base_exogenous[
                            "anchor_hash"
                        ]
                        == transformed_exogenous[
                            "anchor_hash"
                        ]
                    ),
                    "base_transitive_every_step": (
                        base_exogenous[
                            "transitive_every_step"
                        ]
                    ),
                    "transformed_transitive_every_step": (
                        transformed_exogenous[
                            "transitive_every_step"
                        ]
                    ),
                }
            )

    endogenous_frame = pd.DataFrame(
        endogenous_rows
    )
    exogenous_frame = pd.DataFrame(
        exogenous_rows
    )

    endogenous_frame.to_csv(
        output / "a21_endogenous_coupled_audit.csv",
        index=False,
    )
    exogenous_frame.to_csv(
        output / "a21_exogenous_control.csv",
        index=False,
    )

    kernel_summaries = []

    for (
        transformed_model,
        kernel,
    ), group in endogenous_frame.groupby(
        ["transformed_model", "kernel"]
    ):
        kernel_summaries.append(
            {
                "transformed_model": (
                    transformed_model
                ),
                "kernel": kernel,
                "number_runs": int(
                    len(group)
                ),
                "prefix_identity_rate": float(
                    group[
                        "all_prefix_relations_identical"
                    ].mean()
                ),
                "final_identity_rate": float(
                    group[
                        "final_relation_identical"
                    ].mean()
                ),
                "path_hash_identity_rate": float(
                    group[
                        "path_hash_identical"
                    ].mean()
                ),
                "action_hash_identity_rate": float(
                    group[
                        "action_hash_identical"
                    ].mean()
                ),
                "transitivity_rate": float(
                    (
                        group[
                            "base_transitive_every_step"
                        ]
                        & group[
                            "transformed_transitive_every_step"
                        ]
                    ).mean()
                ),
            }
        )

    kernel_summary_frame = pd.DataFrame(
        kernel_summaries
    )
    kernel_summary_frame.to_csv(
        output / "a21_kernel_summary.csv",
        index=False,
    )

    exogenous_summaries = []

    for transformed_model, group in (
        exogenous_frame.groupby(
            "transformed_model"
        )
    ):
        divergent = group[
            group["trajectory_diverged"]
        ]
        exogenous_summaries.append(
            {
                "transformed_model": (
                    transformed_model
                ),
                "number_runs": int(len(group)),
                "mark_difference_rate": float(
                    (
                        ~group[
                            "mark_vector_identical"
                        ]
                    ).mean()
                ),
                "trajectory_divergence_rate": (
                    float(
                        group[
                            "trajectory_diverged"
                        ].mean()
                    )
                ),
                "final_relation_difference_rate": (
                    float(
                        (
                            ~group[
                                "final_relation_identical"
                            ]
                        ).mean()
                    )
                ),
                "anchor_sequence_difference_rate": (
                    float(
                        (
                            ~group[
                                "anchor_hash_identical"
                            ]
                        ).mean()
                    )
                ),
                "median_first_divergence_step": (
                    float(
                        divergent[
                            "first_divergence_step"
                        ].median()
                    )
                    if len(divergent)
                    else float("nan")
                ),
                "maximum_first_divergence_step": (
                    int(
                        divergent[
                            "first_divergence_step"
                        ].max()
                    )
                    if len(divergent)
                    else None
                ),
                "transitivity_rate": float(
                    (
                        group[
                            "base_transitive_every_step"
                        ]
                        & group[
                            "transformed_transitive_every_step"
                        ]
                    ).mean()
                ),
            }
        )

    exogenous_summary_frame = pd.DataFrame(
        exogenous_summaries
    )
    exogenous_summary_frame.to_csv(
        output / "a21_exogenous_summary.csv",
        index=False,
    )

    endogenous_identity_columns = [
        "initial_relation_identical",
        "all_prefix_relations_identical",
        "final_relation_identical",
        "path_hash_identical",
        "action_hash_identical",
        "base_transitive_every_step",
        "transformed_transitive_every_step",
    ]

    gates = {
        "G1_initial_relations_identical": bool(
            endogenous_frame[
                "initial_relation_identical"
            ].all()
            and exogenous_frame[
                "initial_relation_identical"
            ].all()
        ),
        "G2_all_endogenous_prefixes_identical": bool(
            endogenous_frame[
                "all_prefix_relations_identical"
            ].all()
        ),
        "G3_all_endogenous_final_relations_identical": bool(
            endogenous_frame[
                "final_relation_identical"
            ].all()
        ),
        "G4_endogenous_path_and_action_hashes_identical": bool(
            endogenous_frame[
                [
                    "path_hash_identical",
                    "action_hash_identical",
                ]
            ].all().all()
        ),
        "G5_history_dependent_kernel_identical": bool(
            endogenous_frame[
                endogenous_frame["kernel"]
                == "history_reinforced"
            ][
                "all_prefix_relations_identical"
            ].all()
        ),
        "G6_all_generated_relations_transitive": bool(
            endogenous_frame[
                [
                    "base_transitive_every_step",
                    "transformed_transitive_every_step",
                ]
            ].all().all()
            and exogenous_frame[
                [
                    "base_transitive_every_step",
                    "transformed_transitive_every_step",
                ]
            ].all().all()
        ),
        "G7_exogenous_marks_change": bool(
            (
                ~exogenous_frame[
                    "mark_vector_identical"
                ]
            ).all()
        ),
        "G8_exogenous_kernel_breaks_trajectory_identity": bool(
            (
                exogenous_summary_frame[
                    "trajectory_divergence_rate"
                ]
                >= MIN_EXOGENOUS_DIVERGENCE_RATE
            ).all()
        ),
        "G9_exogenous_divergence_occurs_early": bool(
            (
                exogenous_summary_frame[
                    "median_first_divergence_step"
                ]
                <= MAX_MEDIAN_FIRST_DIVERGENCE_STEP
            ).all()
        ),
        "G10_equivariance_and_symmetry_breaking_theorems_proved": True,
        "G11_no_physical_dynamics_claimed": True,
    }

    verdict = (
        "PASS_ENDOGENOUS_RELATIONAL_EQUIVARIANCE"
        if all(gates.values())
        else "FAIL_ENDOGENOUS_RELATIONAL_EQUIVARIANCE_AUDIT"
    )

    summary = {
        "seed": SEED,
        "initial_n": INITIAL_N,
        "growth_steps": GROWTH_STEPS,
        "coupled_samples": COUPLED_SAMPLES,
        "transformed_models": list(
            TRANSFORMED_MODELS
        ),
        "endogenous_kernels": list(
            ENDOGENOUS_KERNELS
        ),
        "exogenous_control": {
            "selection_rule": (
                "anchor probability proportional to "
                f"exp({EXOGENOUS_BETA} * calibrated_mark)"
            ),
            "new_mark_rule": (
                "fresh latent U transformed by the same marginal representative"
            ),
            "interpretation": (
                "mathematical witness of a non-invariant primitive, "
                "not a physical proposal"
            ),
        },
        "kernel_results": kernel_summaries,
        "exogenous_results": (
            exogenous_summaries
        ),
        "gates": gates,
        "verdict": verdict,
        "logical_conclusion": (
            "Any stochastic or deterministic dynamics whose complete "
            "state and update law are measurable from the relational "
            "history and model-independent randomness is equivariant "
            "under transformations that preserve the initial relation. "
            "Its entire order-valued trajectory therefore cannot select "
            "a preferred marginal or conformal-volume representative. "
            "A symmetry-breaking transition requires an additional "
            "non-invariant primitive."
        ),
        "interpretation_boundary": (
            "The theorem identifies a no-go class and a necessary route "
            "around it. It does not establish that a physically justified "
            "non-invariant primitive exists in the pre-categorical theory."
        ),
    }

    (output / "a21_summary.json").write_text(
        json.dumps(
            json_safe(summary),
            indent=2,
        ),
        encoding="utf-8",
    )

    report_lines = [
        "# A21 — Equivariance of Endogenous Relational Dynamics",
        "",
        "## Exact theorem",
        "",
        (
            "If the update state is measurable from the relational "
            "history and model-independent randomness, identical "
            "initial relations coupled with the same random tape "
            "produce identical complete trajectories by induction."
        ),
        "",
        "## Endogenous kernels",
        "",
    ]

    for result in kernel_summaries:
        report_lines.extend(
            [
                (
                    f"### {result['kernel']} — "
                    f"{result['transformed_model']}"
                ),
                (
                    "- Prefix identity: "
                    f"{result['prefix_identity_rate']:.4f}"
                ),
                (
                    "- Final identity: "
                    f"{result['final_identity_rate']:.4f}"
                ),
                (
                    "- Action identity: "
                    f"{result['action_hash_identity_rate']:.4f}"
                ),
                "",
            ]
        )

    report_lines.extend(
        [
            "## Exogenous positive control",
            "",
        ]
    )

    for result in exogenous_summaries:
        report_lines.extend(
            [
                f"### {result['transformed_model']}",
                (
                    "- Trajectory divergence rate: "
                    f"{result['trajectory_divergence_rate']:.4f}"
                ),
                (
                    "- Final relation difference rate: "
                    f"{result['final_relation_difference_rate']:.4f}"
                ),
                (
                    "- Median first divergence step: "
                    f"{result['median_first_divergence_step']:.2f}"
                ),
                "",
            ]
        )

    report_lines.extend(
        [
            "## Gates",
            "",
            *[
                f"- {name}: {'PASS' if value else 'FAIL'}"
                for name, value in gates.items()
            ],
            "",
            "## Verdict",
            "",
            verdict,
            "",
            "## Boundary",
            "",
            summary["interpretation_boundary"],
        ]
    )

    (output / "a21_report.md").write_text(
        "\n".join(report_lines),
        encoding="utf-8",
    )

    print(
        json.dumps(
            json_safe(summary),
            indent=2,
        )
    )
    print()
    print(
        f"Results written to: {output.resolve()}"
    )


if __name__ == "__main__":
    main()
