#!/usr/bin/env python3
"""A6 — exact audit of extra non-geometric symmetries at finite size.

Uses loopless directed graph isomorphism classes and computes the dimensions
of probability simplices invariant under:
- direction reversal A -> A^T,
- edge complement A -> J-I-A,
- the Klein four group generated by both.

These are candidate static symmetries only; the script does not assert they
are physically justified.
"""
from __future__ import annotations

import itertools
import json
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

N_MAX = 4
OUT = Path('/mnt/data/a6_exact_results')
OUT.mkdir(parents=True, exist_ok=True)


def edge_list(n: int):
    return [(i,j) for i in range(n) for j in range(n) if i != j]


def mask_to_adj(mask: int, n: int) -> np.ndarray:
    A=np.zeros((n,n),dtype=np.uint8)
    for b,(i,j) in enumerate(edge_list(n)):
        A[i,j]=(mask>>b)&1
    return A


def adj_to_mask(A: np.ndarray) -> int:
    m=0; n=A.shape[0]
    for b,(i,j) in enumerate(edge_list(n)):
        if A[i,j]: m|=1<<b
    return m


def permuted_mask(mask: int,n:int,p:Tuple[int,...])->int:
    A=mask_to_adj(mask,n); B=np.zeros_like(A)
    for i in range(n):
        for j in range(n):
            B[p[i],p[j]]=A[i,j]
    return adj_to_mask(B)


def canonical(mask:int,n:int)->int:
    return min(permuted_mask(mask,n,p) for p in itertools.permutations(range(n)))


def classes(n:int)->List[int]:
    return sorted({canonical(mask,n) for mask in range(1<<(n*(n-1)))})


def reverse(mask:int,n:int)->int:
    return adj_to_mask(mask_to_adj(mask,n).T)


def complement(mask:int,n:int)->int:
    A=mask_to_adj(mask,n)
    B=np.ones_like(A)-np.eye(n,dtype=np.uint8)-A
    return adj_to_mask(B)


def orbit_count(reps:List[int], n:int, generators)->Tuple[int,List[int]]:
    rep_set=set(reps)
    unseen=set(reps)
    sizes=[]
    while unseen:
        x=next(iter(unseen))
        orbit={x}; frontier=[x]
        while frontier:
            y=frontier.pop()
            for g in generators:
                z=canonical(g(y,n),n)
                if z not in orbit:
                    orbit.add(z); frontier.append(z)
        unseen-=orbit
        sizes.append(len(orbit))
    return len(sizes), sorted(sizes)


def main():
    results=[]
    for n in range(1,N_MAX+1):
        reps=classes(n)
        identity=lambda m,k:m
        groups={
            'none':[identity],
            'reversal':[identity,reverse],
            'complement':[identity,complement],
            'reversal_and_complement':[identity,reverse,complement,lambda m,k: reverse(complement(m,k),k)],
        }
        row={'n':n,'u_n':len(reps),'groups':{}}
        for name,gens in groups.items():
            count,sizes=orbit_count(reps,n,gens)
            row['groups'][name]={
                'class_orbits':count,
                'invariant_simplex_dimension':count-1,
                'orbit_size_histogram':{str(s):sizes.count(s) for s in sorted(set(sizes))},
            }
        results.append(row)
    summary={
        'model':'loopless directed graph isomorphism classes',
        'warning':'Symmetries audited here are candidate assumptions, not derived physical principles.',
        'results':results,
        'continuum_counterfamily':{
            'description':'Independent directed Erdos-Renyi laws indexed by p in (0,1) are exchangeable and projective.',
            'distinguishing_observable':'Expected directed edge density equals p.',
            'consequence':'Exchangeability plus projectivity plus nondegeneracy does not select a unique law.'
        }
    }
    (OUT/'a6_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')
    print(json.dumps(summary,indent=2))

if __name__=='__main__': main()
